"""Excel column mapping settings."""

from __future__ import annotations

from typing import Final

TARGET_FIELDS: Final[list[str]] = [
    "product_name",
    "product_code",
    "price",
    "safety_stock",
    "description",
    "stock",
    "inbound_date",
    "last_outbound_date",
    "category",
    "brand",
    "warehouse",
    "supplier",
    "status",
    "quality_status",
]

COLUMN_SYNONYMS: Final[dict[str, list[str]]] = {
    "product_name": [
        "상품명",
        "제품명",
        "품명",
        "품목명",
        "상품",
        "제품",
        "모델명",
        "모델",
        "name",
        "product",
        "item",
    ],
    "product_code": [
        "상품코드",
        "제품코드",
        "품목코드",
        "코드",
        "sku",
        "product_code",
        "item_code",
        "code",
        "생산LOT",
        "생산 lot",
        "lot",
    ],
    "price": [
        "가격",
        "금액",
        "단가",
        "판매가",
        "원가",
        "비용",
        "price",
        "cost",
        "amount",
    ],
    "description": [
        "설명",
        "상세설명",
        "상품설명",
        "비고",
        "메모",
        "description",
        "desc",
        "note",
    ],
    "stock": [
        "재고",
        "재고수량",
        "수량",
        "잔여수량",
        "보유수량",
        "현재고",
        "stock",
        "qty",
        "quantity",
        "금일생산수량",
        "일생산량",
        "완료수량",
        "금일누적생산수",
        "누적생산수",
        "실시간누적생산",
    ],
    "safety_stock": [
        "안전재고",
        "적정재고",
        "최소재고",
        "기준재고",
        "safety_stock",
        "safety stock",
        "minimum_stock",
        "목표수량",
        "계획수량",
    ],
    "inbound_date": [
        "입고일",
        "입고일자",
        "입고날짜",
        "inbound_date",
        "received_date",
        "receipt_date",
        "작업시작일",
        "생산시작일",
    ],
    "last_outbound_date": [
        "최근출고일",
        "최종출고일",
        "마지막출고일",
        "출고일",
        "출고일자",
        "last_outbound_date",
        "last_shipped_date",
        "outbound_date",
        "최종검사일시",
        "최종검사일",
        "실시간갱신시각",
        "데이터갱신시각",
        "최종갱신시각",
    ],
    "category": [
        "카테고리",
        "분류",
        "구분",
        "category",
        "type",
        "제품군",
    ],
    "brand": [
        "브랜드",
        "제조사",
        "회사",
        "brand",
        "maker",
        "manufacturer",
    ],
    "warehouse": [
        "창고",
        "물류센터",
        "보관위치",
        "저장위치",
        "warehouse",
        "location",
        "생산라인",
        "라인",
        "공정라인",
    ],
    "supplier": [
        "공급업체",
        "거래처",
        "납품업체",
        "vendor",
        "supplier",
        "자재공급사",
    ],
    "status": [
        "상태",
        "status",
        "가동상태",
        "작업상태",
    ],
    "quality_status": [
        "품질결과",
        "품질판정",
        "QC결과",
        "검사결과",
        "실시간품질",
        "quality_status",
        "qc_result",
    ],
}
